name = "modpackFabricLatest"
author = "Bradman1985"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cfa86547cfb93369aa44d05e32ea28b322c02b51d65ef010d7807297aa1f79a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
